# Generated by Django 4.2.26 on 2025-11-18 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediafile',
            name='thumbnail',
        ),
    ]
