# Generated by Django 4.2.26 on 2025-11-30 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0002_remove_mediafile_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediafile',
            name='album',
        ),
        migrations.CreateModel(
            name='AlbumMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album_media', to='albums.album')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album_media', to='albums.mediafile')),
            ],
            options={
                'verbose_name_plural': 'Album Media',
                'unique_together': {('album', 'media')},
            },
        ),
    ]
