# Generated by Django 4.2.26 on 2025-11-30 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0003_remove_mediafile_album_albummedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafile',
            name='original_filename',
            field=models.CharField(blank=True, help_text='Original filename uploaded by user', max_length=500),
        ),
    ]
